# Generated by Django 2.0.4 on 2020-05-27 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sign_io', '0001_initial'),
        ('fileManager', '0003_auto_20200527_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classVector', models.CharField(max_length=255, verbose_name='classVector')),
                ('filemap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileManager.FileMap')),
            ],
            options={
                'db_table': 'fileNode',
            },
        ),
        migrations.CreateModel(
            name='NodeMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeName', models.CharField(max_length=255, verbose_name='nodeName')),
                ('nodeValue', models.IntegerField(verbose_name='nodeValue')),
                ('fnodemap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowNet.FileNode')),
            ],
            options={
                'db_table': 'nodeMap',
            },
        ),
        migrations.CreateModel(
            name='UserNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classVector', models.CharField(max_length=255, verbose_name='classVector')),
                ('usermap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign_io.User')),
            ],
            options={
                'db_table': 'UserNodes',
            },
        ),
        migrations.AddField(
            model_name='nodemap',
            name='unodemap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowNet.UserNode'),
        ),
    ]
