# Generated by Django 2.0.4 on 2020-05-28 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowNet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='filenode',
            table='fileNodes',
        ),
        migrations.AlterModelTable(
            name='usernode',
            table='userNodes',
        ),
    ]
