# Generated by Django 2.0.4 on 2020-05-20 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sign_io', '0001_initial'),
        ('fileManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamDirId', models.IntegerField(default=0, verbose_name='teamDirId')),
                ('filemap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileManager.FileMap')),
            ],
            options={
                'db_table': 'teamFiles',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('teamId', models.IntegerField(primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=20, unique=True, verbose_name='teamName')),
                ('buildTime', models.DateTimeField(verbose_name='buildTime')),
                ('memberMax', models.IntegerField(default=10, verbose_name='memberMax')),
                ('headPic', models.CharField(default='../../../assets/default-head.jpg', max_length=255, verbose_name='headPic')),
                ('notice', models.CharField(blank=True, max_length=255, verbose_name='notice')),
                ('teamType', models.IntegerField(default=0, verbose_name='teamType')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign_io.User')),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign_io.User')),
                ('teammap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Teams')),
            ],
            options={
                'db_table': 'userTeam',
            },
        ),
        migrations.AddField(
            model_name='teamfile',
            name='teammap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Teams'),
        ),
        migrations.AlterUniqueTogether(
            name='userteam',
            unique_together={('teammap', 'member')},
        ),
    ]
