# Generated by Django 2.0.4 on 2020-05-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='fileClass',
            field=models.IntegerField(default=-1, verbose_name='fileClass'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='commitMsg',
            field=models.CharField(blank=True, max_length=300, verbose_name='commitMsg'),
        ),
    ]
