# Generated by Django 2.0.4 on 2020-05-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileManager', '0002_auto_20200523_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='fileName',
            field=models.CharField(max_length=255, verbose_name='fileName'),
        ),
    ]
