# Generated by Django 2.0.4 on 2020-06-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileManager', '0003_auto_20200527_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemap',
            name='fileMd5',
            field=models.CharField(max_length=255, verbose_name='fileMd5'),
        ),
    ]
