# Generated by Django 2.0.4 on 2020-05-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('buildTime', models.DateTimeField(verbose_name='buildTime')),
                ('headPic', models.CharField(default='../../../assets/default-head.jpg', max_length=255, verbose_name='headPic')),
                ('readme', models.CharField(blank=True, max_length=255, verbose_name='readme')),
                ('mood', models.CharField(blank=True, max_length=255, verbose_name='mood')),
                ('job', models.IntegerField(default=0, verbose_name='job')),
                ('place', models.CharField(blank=True, max_length=50, verbose_name='place')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, verbose_name='email')),
                ('code', models.IntegerField(verbose_name='code')),
                ('askTime', models.DateTimeField(auto_now=True, verbose_name='askTime')),
                ('failureTime', models.DateTimeField(verbose_name='failureTime')),
            ],
            options={
                'db_table': 'codeTable',
            },
        ),
    ]
