# Generated by Django 2.0.4 on 2020-05-20 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sign_io', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='sign_io.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='sign_io.User')),
            ],
            options={
                'db_table': 'follower',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300, verbose_name='message')),
                ('msgTime', models.DateTimeField(verbose_name='msgTime')),
                ('msgType', models.IntegerField(default=0, verbose_name='msgType')),
                ('msgBits', models.IntegerField(default=0, verbose_name='msgBits')),
                ('userFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userFrom', to='sign_io.User')),
                ('userTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userTo', to='sign_io.User')),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('user', 'follower')},
        ),
    ]
